name: Lab 12 - Rust
on:
  push:
    paths:
      - 'module12/**'
  pull_request:
    paths:
      - 'module12/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: Run cargo test
        run: cd module12 && cargo test --verbose
      - name: Run cargo fmt check
        run: cd module12 && cargo fmt --check
      - name: Run cargo clippy
        run: cd module12 && cargo clippy -- -D warnings
